service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: batch-service-1-4d2eme4zvd
  name: batch-service-1-4d2eme4zvd
  selector: batch-service-1-4d2eme4zvd
  type:
  - ClusterIP
  - NodePort
namespace: fewf-dev
batch:
  name: batch-service-1-4d2eme4zvd
  image:
    name: batch-service-1-4d2eme4zvd
    tag: lastest
    secret: regsecret
  container:
    name: batch-service-1-4d2eme4zvd
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  backing: 
  volume:
    name: pvc-batch-service-1-4d2eme4zvd
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
pvc:
  name: pvc-batch-service-1-4d2eme4zvd
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
